INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_LETS_TEST_SOME_STUFF lets_test_some_stuff)

FIND_PATH(
    LETS_TEST_SOME_STUFF_INCLUDE_DIRS
    NAMES lets_test_some_stuff/api.h
    HINTS $ENV{LETS_TEST_SOME_STUFF_DIR}/include
        ${PC_LETS_TEST_SOME_STUFF_INCLUDEDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/include
          /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    LETS_TEST_SOME_STUFF_LIBRARIES
    NAMES gnuradio-lets_test_some_stuff
    HINTS $ENV{LETS_TEST_SOME_STUFF_DIR}/lib
        ${PC_LETS_TEST_SOME_STUFF_LIBDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/lib
          ${CMAKE_INSTALL_PREFIX}/lib64
          /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LETS_TEST_SOME_STUFF DEFAULT_MSG LETS_TEST_SOME_STUFF_LIBRARIES LETS_TEST_SOME_STUFF_INCLUDE_DIRS)
MARK_AS_ADVANCED(LETS_TEST_SOME_STUFF_LIBRARIES LETS_TEST_SOME_STUFF_INCLUDE_DIRS)

